import tkinter as tk
from tkinter import *
from tkinter import ttk
from math import *
import itertools

pressed = False
i = 1
ic = 1

BLUE = []
RED = []

def press(n, pa):
    global BLUE
    global RED
    global i
    global ic
    paa = pa
    a = n
    pressed = True
    if pressed == True:
        b = a + ".config(state=DISABLED)"
        exec(b)
        pressed = False
        upbutt = int(a.replace('x', '')) - 1
        if upbutt != 10 and upbutt != 20 and upbutt != 30 and upbutt != 40 and upbutt != 50 and upbutt != 60 and upbutt != 70:
            ba = "x" + str(upbutt)
            bb = ba + ".config(state=NORMAL)"
            exec(bb)
    if i == 1:
        t = a + ".config(bg='blue')"
        exec(t)
        abab = int(a.replace('x', ''))
        BLUE.append(abab)
        BLUE.sort()
        pipa = paa + ".config(text='Na vrsti je rdec.')"
        exec(pipa)
        i = i + 1
    else:
        r = a + ".config(bg='red')"
        exec(r)
        acac = int(a.replace('x', ''))
        RED.append(acac)
        RED.sort()
        pipa = paa + ".config(text='Na vrsti je moder.')"
        exec(pipa)
        i = i - 1

def win(pepa):
    global BLUE
    global RED
    for combination in itertools.combinations(BLUE, 4):
        i1b = str(combination)[1] + str(combination)[2]
        i2b = str(combination)[5] + str(combination)[6]
        i3b = str(combination)[9] + str(combination)[10]
        i4b = str(combination)[13] + str(combination)[14]
        if int(i1b) == int(i2b) - 10 and int(i2b) == int(i3b) - 10 and int(i3b) == int(i4b) - 10:
            biw = pepa + ".config(text='Zmagal je moder.')"
            exec(biw)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)
        if int(i1b) == int(i2b) - 1 and int(i2b) == int(i3b) - 1 and int(i3b) == int(i4b) - 1:
            biw = pepa + ".config(text='Zmagal je moder.')"
            exec(biw)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)
        if int(i1b) == int(i2b) - 9 and int(i2b) == int(i3b) - 9 and int(i3b) == int(i4b) - 9:
            biw = pepa + ".config(text='Zmagal je moder.')"
            exec(biw)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)
        if int(i1b) == int(i2b) - 11 and int(i2b) == int(i3b) - 11 and int(i3b) == int(i4b) - 11:
            biw = pepa + ".config(text='Zmagal je moder.')"
            exec(biw)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)
    for combination in itertools.combinations(RED, 4):
        i1a = str(combination)[1] + str(combination)[2]
        i2a = str(combination)[5] + str(combination)[6]
        i3a = str(combination)[9] + str(combination)[10]
        i4a = str(combination)[13] + str(combination)[14]
        if int(i1a) == int(i2a) - 10 and int(i2a) == int(i3a) - 10 and int(i3a) == int(i4a) - 10:
            bew = pepa + ".config(text='Zmagal je rdec.')"
            exec(bew)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)
        if int(i1a) == int(i2a) - 1 and int(i2a) == int(i3a) - 1 and int(i3a) == int(i4a) - 1:
            bew = pepa + ".config(text='Zmagal je rdec.')"
            exec(bew)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)
        if int(i1a) == int(i2a) - 9 and int(i2a) == int(i3a) - 9 and int(i3a) == int(i4a) - 9:
            bew = pepa + ".config(text='Zmagal je rdec.')"
            exec(bew)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)
        if int(i1a) == int(i2a) - 11 and int(i2a) == int(i3a) - 11 and int(i3a) == int(i4a) - 11:
            bew = pepa + ".config(text='Zmagal je rdec.')"
            exec(bew)
            x11.config(state=DISABLED)
            x12.config(state=DISABLED)
            x13.config(state=DISABLED)
            x14.config(state=DISABLED)
            x15.config(state=DISABLED)
            x16.config(state=DISABLED)
            x21.config(state=DISABLED)
            x22.config(state=DISABLED)
            x23.config(state=DISABLED)
            x24.config(state=DISABLED)
            x25.config(state=DISABLED)
            x26.config(state=DISABLED)
            x31.config(state=DISABLED)
            x32.config(state=DISABLED)
            x33.config(state=DISABLED)
            x34.config(state=DISABLED)
            x35.config(state=DISABLED)
            x36.config(state=DISABLED)
            x41.config(state=DISABLED)
            x42.config(state=DISABLED)
            x43.config(state=DISABLED)
            x44.config(state=DISABLED)
            x45.config(state=DISABLED)
            x46.config(state=DISABLED)
            x51.config(state=DISABLED)
            x52.config(state=DISABLED)
            x53.config(state=DISABLED)
            x54.config(state=DISABLED)
            x55.config(state=DISABLED)
            x56.config(state=DISABLED)
            x61.config(state=DISABLED)
            x62.config(state=DISABLED)
            x63.config(state=DISABLED)
            x64.config(state=DISABLED)
            x65.config(state=DISABLED)
            x66.config(state=DISABLED)
            x71.config(state=DISABLED)
            x72.config(state=DISABLED)
            x73.config(state=DISABLED)
            x74.config(state=DISABLED)
            x75.config(state=DISABLED)
            x76.config(state=DISABLED)


A = tk.Tk()
A.title("STIRI V VRSTO")

zmagovalec = Label(A, text="Na vrsti je moder.")
x11 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x11", p = "zmagovalec": [press(x, p), win(p)])
x12 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x12", p = "zmagovalec": [press(x, p), win(p)])
x13 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x13", p = "zmagovalec": [press(x, p), win(p)])
x14 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x14", p = "zmagovalec": [press(x, p), win(p)])
x15 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x15", p = "zmagovalec": [press(x, p), win(p)])
x16 = tk.Button(A, width=15, height=7, state=NORMAL, command=lambda x = "x16", p = "zmagovalec": [press(x, p), win(p)])
x21 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x21", p = "zmagovalec": [press(x, p), win(p)])
x22 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x22", p = "zmagovalec": [press(x, p), win(p)])
x23 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x23", p = "zmagovalec": [press(x, p), win(p)])
x24 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x24", p = "zmagovalec": [press(x, p), win(p)])
x25 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x25", p = "zmagovalec": [press(x, p), win(p)])
x26 = tk.Button(A, width=15, height=7, state=NORMAL, command=lambda x = "x26", p = "zmagovalec": [press(x, p), win(p)])
x31 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x31", p = "zmagovalec": [press(x, p), win(p)])
x32 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x32", p = "zmagovalec": [press(x, p), win(p)])
x33 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x33", p = "zmagovalec": [press(x, p), win(p)])
x34 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x34", p = "zmagovalec": [press(x, p), win(p)])
x35 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x35", p = "zmagovalec": [press(x, p), win(p)])
x36 = tk.Button(A, width=15, height=7, state=NORMAL, command=lambda x = "x36", p = "zmagovalec": [press(x, p), win(p)])
x41 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x41", p = "zmagovalec": [press(x, p), win(p)])
x42 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x42", p = "zmagovalec": [press(x, p), win(p)])
x43 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x43", p = "zmagovalec": [press(x, p), win(p)])
x44 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x44", p = "zmagovalec": [press(x, p), win(p)])
x45 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x45", p = "zmagovalec": [press(x, p), win(p)])
x46 = tk.Button(A, width=15, height=7, state=NORMAL, command=lambda x = "x46", p = "zmagovalec": [press(x, p), win(p)])
x51 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x51", p = "zmagovalec": [press(x, p), win(p)])
x52 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x52", p = "zmagovalec": [press(x, p), win(p)])
x53 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x53", p = "zmagovalec": [press(x, p), win(p)])
x54 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x54", p = "zmagovalec": [press(x, p), win(p)])
x55 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x55", p = "zmagovalec": [press(x, p), win(p)])
x56 = tk.Button(A, width=15, height=7, state=NORMAL, command=lambda x = "x56", p = "zmagovalec": [press(x, p), win(p)])
x61 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x61", p = "zmagovalec": [press(x, p), win(p)])
x62 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x62", p = "zmagovalec": [press(x, p), win(p)])
x63 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x63", p = "zmagovalec": [press(x, p), win(p)])
x64 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x64", p = "zmagovalec": [press(x, p), win(p)])
x65 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x65", p = "zmagovalec": [press(x, p), win(p)])
x66 = tk.Button(A, width=15, height=7, state=NORMAL, command=lambda x = "x66", p = "zmagovalec": [press(x, p), win(p)])
x71 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x71", p = "zmagovalec": [press(x, p), win(p)])
x72 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x72", p = "zmagovalec": [press(x, p), win(p)])
x73 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x73", p = "zmagovalec": [press(x, p), win(p)])
x74 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x74", p = "zmagovalec": [press(x, p), win(p)])
x75 = tk.Button(A, width=15, height=7, state=DISABLED, command=lambda x = "x75", p = "zmagovalec": [press(x, p), win(p)])
x76 = tk.Button(A, width=15, height=7, state=NORMAL, command=lambda x = "x76", p = "zmagovalec": [press(x, p), win(p)])

zmagovalec.grid(column=4, row=7)
x11.grid(column= 1, row= 1)
x12.grid(column= 1, row= 2)
x13.grid(column= 1, row= 3)
x14.grid(column= 1, row= 4)
x15.grid(column= 1, row= 5)
x16.grid(column= 1, row= 6)
x21.grid(column= 2, row= 1)
x22.grid(column= 2, row= 2)
x23.grid(column= 2, row= 3)
x24.grid(column= 2, row= 4)
x25.grid(column= 2, row= 5)
x26.grid(column= 2, row= 6)
x31.grid(column= 3, row= 1)
x32.grid(column= 3, row= 2)
x33.grid(column= 3, row= 3)
x34.grid(column= 3, row= 4)
x35.grid(column= 3, row= 5)
x36.grid(column= 3, row= 6)
x41.grid(column= 4, row= 1)
x42.grid(column= 4, row= 2)
x43.grid(column= 4, row= 3)
x44.grid(column= 4, row= 4)
x45.grid(column= 4, row= 5)
x46.grid(column= 4, row= 6)
x51.grid(column= 5, row= 1)
x52.grid(column= 5, row= 2)
x53.grid(column= 5, row= 3)
x54.grid(column= 5, row= 4)
x55.grid(column= 5, row= 5)
x56.grid(column= 5, row= 6)
x61.grid(column= 6, row= 1)
x62.grid(column= 6, row= 2)
x63.grid(column= 6, row= 3)
x64.grid(column= 6, row= 4)
x65.grid(column= 6, row= 5)
x66.grid(column= 6, row= 6)
x71.grid(column= 7, row= 1)
x72.grid(column= 7, row= 2)
x73.grid(column= 7, row= 3)
x74.grid(column= 7, row= 4)
x75.grid(column= 7, row= 5)
x76.grid(column= 7, row= 6)

A.resizable(width=False, height=False)
A.mainloop()